# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Antonbl
tagline:             'A data scientist'
description:         'A blog to discuss my ideas'
url:                 http://antonbl.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Anton Bubna-Litic
  url:               https://twitter.com/antonbubnalitic
  email:             anton.bubna.litic@gmail.com

# Custom vars
version:             1.0.0
